### ISSUE TITLE
Does not run.

### ISSUE THREAD

**Issue by aeschylus** [begriffs/immutube#2]
I can only get some device video. Searching returns some kind of dependency error.

**Comment by begriffs** [comment]
@DrBoolean can I transfer maintenance of this project to you?

**Comment by aeschylus** [comment]
![screen shot 2015-05-19 at 17 43 26](https://cloud.githubusercontent.com/assets/145874/7716986/9e56f172-fe4e-11e4-9718-4588dab395a6.png)

**Comment by aeschylus** [comment]
Presumably the API changed, or something.

Just starting the course, so it may be that I can deal with the problem once I understand more about the app through the tutorials.

**Comment by DrBoolean** [comment]
I'll take a look!

**Comment by DrBoolean** [comment]
Yeah, looks totally busted. The flickr example does about the same thing anyways. I think it's time to say goodbye to this one. Flickr is here: https://github.com/DrBoolean/hardcorejs/tree/master/demos/step1

**Comment by DrBoolean** [comment]
Just wanted to mention, i added the api key to fix this.

**Comment by aeschylus** [comment]
Thanks! I'll give it a try.

**Comment by aeschylus** [comment]
Yep, it works now. Fortunate it was something so simple. Thanks for the quick fix.

**Comment by DrBoolean** [comment]
Happy to help! Thanks for alerting me. It's getting a bit outdated since ramda has added so much... I'll probably update it over the weekend.
